# Generated by Django 5.0.3 on 2026-03-31 09:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fssai_license', models.CharField(blank=True, max_length=50, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant_version', models.CharField(default='v1', max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'is_open'], name='restaurant__is_acti_5247ca_idx'), models.Index(fields=['city', 'is_active'], name='restaurant__city_937f48_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('zone_version', models.CharField(default='v1', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='restaurant.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('table_number', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('qr_code_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('table_type', models.CharField(choices=[('standard', 'Standard Table'), ('counter', 'Counter / Takeaway'), ('delivery', 'Delivery Placeholder')], default='standard', max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('occupied_by_user_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('is_reserved_manual', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_version', models.CharField(default='v1', max_length=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='restaurant.restaurantzone')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('reservation_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=90)),
                ('end_time', models.DateTimeField(editable=False)),
                ('guest_count', models.PositiveIntegerField(default=2)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('seated', 'Seated (Active)'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_version', models.CharField(default='v1', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurant.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='restaurant.table')),
            ],
            options={
                'ordering': ['-reservation_time'],
            },
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['restaurant', 'is_active'], name='restaurant__restaur_647884_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['table_type'], name='restaurant__table_t_78a2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['restaurant', 'zone'], name='restaurant__restaur_66ebae_idx'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('restaurant', 'table_number'), name='unique_table_number_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['restaurant', 'reservation_time'], name='restaurant__restaur_e64f67_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['table', 'reservation_time'], name='restaurant__table_i_ddb9e8_idx'),
        ),
    ]
