apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
  namespace: dineflow-dev
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: menu-service

  template:
    metadata:
      labels:
        app: menu-service

    spec:
      initContainers:
        - name: init-menu-db
          image: postgres:15
          imagePullPolicy: IfNotPresent
          env:
            - name: PGPASSWORD
              value: postgres
          command:
            - sh
            - -c
            - |
              echo "Waiting for Postgres..."
              until pg_isready -h menu-db -U postgres; do
              sleep 2
              done

      containers:
        - name: menu-service
          image: dineflow_backend-menu_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: K8S_ENV
              value: "true"
            - name: DB_NAME
              value: "menu_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_HOST
              value: "menu-db"
            - name: DB_PORT
              value: "5432"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: dineflow-dev
spec:
  selector:
    app: menu-service
  ports:
    - port: 8000
      targetPort: 8000