# Generated by Django 6.0.1 on 2026-03-31 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('restaurant_id', models.CharField(db_index=True, max_length=20)),
                ('fcm_token', models.TextField(unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_broadcast', models.BooleanField(default=False)),
                ('is_show', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'topic'], name='firebase_pu_user_id_b5ea22_idx')],
            },
        ),
    ]
