apiVersion: v1
kind: ConfigMap
metadata:
  name: dineflow-config
  namespace: dineflow-dev
data:
  KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"
  REDIS_HOST: "redis" 
  REDIS_PORT: "6379"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres.bqivqoqcgpcsovfcentc"
  POSTGRES_PORT: "6543"
  AWS_DEFAULT_REGION: "ap-south-1"