"""
Django settings for auth_service project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=*t%k4_%ngle&p07u=%nutkznixryt4q_j8qewv&*kz2=7y7lz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "https://dineflow.store",

    # Kubernetes service DNS names
    "auth-service",
    "menu-service",
]

# 🔹 Allow pod IPs only when running inside K8s
if os.getenv("K8S_ENV") == "true":
    ALLOWED_HOSTS.append("*")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "drf_spectacular",
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'restaurant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auth_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auth_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"    
USE_I18N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.CustomUserModel"


K8S_ENV = os.getenv("K8S_ENV") == "true"


if K8S_ENV:
    PRIVATE_KEY_PATH = "/app/jwt_keys/private.pem"
    PUBLIC_KEY_PATH = "/app/jwt_keys/public.pem"
else:
    PRIVATE_KEY_PATH = BASE_DIR / "jwt_keys" / "private.pem"
    PUBLIC_KEY_PATH = BASE_DIR / "jwt_keys" / "public.pem"

try:
    SIMPLE_JWT = {
        "ALGORITHM": "RS256",
        "SIGNING_KEY": open(PRIVATE_KEY_PATH).read(),
        "VERIFYING_KEY": open(PUBLIC_KEY_PATH).read(),
        "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
        "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
        "ROTATE_REFRESH_TOKENS": True,
        "BLACKLIST_AFTER_ROTATION": True,
        "AUTH_HEADER_TYPES": ("Bearer",),
        "AUTH_TOKEN_CLASSES": (
            "rest_framework_simplejwt.tokens.AccessToken",
        ),
        "USER_ID_FIELD": "id",
        "USER_ID_CLAIM": "user_id",
    }
except FileNotFoundError:
    SIMPLE_JWT = {
        "ALGORITHM": "HS256",
        "SIGNING_KEY": "dev-secret-key",
    }


CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# SESSION_COOKIE_DOMAIN = "127.0.0.1"
# CSRF_COOKIE_DOMAIN = "127.0.0.1"

SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = False

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
]


REST_FRAMEWORK = {

    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        'rest_framework.permissions.AllowAny',
    )
}


SPECTACULAR_SETTINGS = {
    "TITLE": "DineFlow – Auth Service API",
    "DESCRIPTION": """
Menu Service for **DineFlow**.

This service handles:
- Authentication
- login
- Register
- All 

🔐 Authentication is enforced at the **API Gateway (NGINX)**.
This service trusts headers injected by the gateway.
    """,
    "VERSION": "1.0.0",

    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
            }
        }
    }
}


# ORDER_SERVICE_TENANT_PROVISION_URL = (
#     "http://order-service.dineflow-dev:8000/internal/tenants/provision"
# )

# MENU_SERVICE_TENANT_PROVISION_URL = (
#     "http://menu-service.dineflow-dev:8000/internal/tenants/provision"
# )

# CART_SERVICE_TENANT_PROVISION_URL = (
#     "http://cart-service.dineflow-dev:8000/internal/tenants/provision"
# )

# KITCHEN_SERVICE_TENANT_PROVISION_URL = (
#     "http://kitchen-service.dineflow-dev:8000/internal/tenants/provision"
# )

# NOTIFICATION_SERVICE_TENANT_PROVISION_URL = (
#     "http://notification-service.dineflow-dev:8000/internal/tenants/provision"
# )


ORDER_SERVICE_TENANT_PROVISION_URL = (
    "http://order-service.dineflow-production:8000/internal/tenants/provision"
)

MENU_SERVICE_TENANT_PROVISION_URL = (
    "http://menu-service.dineflow-production:8000/internal/tenants/provision"
)

CART_SERVICE_TENANT_PROVISION_URL = (
    "http://cart-service.dineflow-production:8000/internal/tenants/provision"
)

KITCHEN_SERVICE_TENANT_PROVISION_URL = (
    "http://kitchen-service.dineflow-production:8000/internal/tenants/provision"
)

NOTIFICATION_SERVICE_TENANT_PROVISION_URL = (
    "http://notification-service.dineflow-production:8000/internal/tenants/provision"
)

KAFKA_BROKER = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")



LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}