"""
Django settings for notification_service project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from celery.schedules import crontab
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(qv*f#ykox)_6q9z^33908phbr0dx-(n(y0zx*hh0@lh@bmz*v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'rest_framework',
    'drf_spectacular',
    "channels",
    'firebase_pushnotification.apps.FirebasePushnotificationConfig',
    'email_service',
    'celery_beat'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "middleware.tenant.TenantSchemaMiddleware",
    "django.middleware.common.CommonMiddleware",
]

if os.getenv("K8S_ENV") == "true":
    ALLOWED_HOSTS.append("*")

ROOT_URLCONF = 'notification_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
            ],
        },
    },
]

WSGI_APPLICATION = 'notification_service.wsgi.application'

ASGI_APPLICATION = "notification_service.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT", "6543"),
        "CONN_MAX_AGE": 0,  # ← Must be 0 for Transaction Pooler
        "OPTIONS": {
            "sslmode": "require",
            "options": "-c search_path=public",  # ← explicit schema
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

KAFKA_BROKER = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")



LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# -------------------------------------
# Internationalization
# -------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"     # Always UTC internally
USE_I18N = True
USE_TZ = True



REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [],
    "UNAUTHENTICATED_USER": None,
}





SPECTACULAR_SETTINGS = {
    "TITLE": "DineFlow – Notification Service API",
    "DESCRIPTION": """
Notification Service for **DineFlow**.

This service handles:
- Add to Notification
- Remove
- Dish images
- Dish reviews

🔐 Authentication is enforced at the **API Gateway (NGINX)**.
This service trusts headers injected by the gateway.
    """,
    "VERSION": "1.0.0",

    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
            }
        }
    }
}



# -------------------------------------
# Celery Configuration
# -------------------------------------


CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = None
CELERY_IGNORE_RESULT = True

CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = "UTC"

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_WORKER_HIJACK_ROOT_LOGGER = False

CELERY_WORKER_LOG_FORMAT = (
    "[%(asctime)s] [%(levelname)s] [%(processName)s] %(message)s"
)

CELERY_WORKER_TASK_LOG_FORMAT = (
    "[%(asctime)s] [%(levelname)s] [%(task_name)s] %(message)s"
)

CELERY_TASK_DEFAULT_QUEUE = "notification_queue"

# For auto clean up the notification

CELERY_BEAT_SCHEDULE = {
    "delete-readed-notifications-every-morning": {
        "task": "celery_beat.tasks.delete_readed_notifications",
        "schedule": crontab(),
        "options": {"queue": "notification_queue"},
    }
}

REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = os.environ.get("REDIS_PORT", "6379")

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"redis://{REDIS_HOST}:{REDIS_PORT}/0"],  # ✅ URL format is cleaner
            "capacity": 1500,
            "expiry": 10,
        },
    },
}