"""
Django settings for notification_service project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from celery.schedules import crontab
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(qv*f#ykox)_6q9z^33908phbr0dx-(n(y0zx*hh0@lh@bmz*v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    "channels",
    'firebase_pushnotification.apps.FirebasePushnotificationConfig',
    'email_service',
    'celery_beat'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'middleware.tenant.TenantSchemaMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if os.getenv("K8S_ENV") == "true":
    ALLOWED_HOSTS.append("*")

ROOT_URLCONF = 'notification_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'notification_service.wsgi.application'

ASGI_APPLICATION = "notification_service.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

KAFKA_BROKER = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")



LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# -------------------------------------
# Internationalization
# -------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"     # Always UTC internally
USE_I18N = True
USE_TZ = True



REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [],
    "UNAUTHENTICATED_USER": None,
}





SPECTACULAR_SETTINGS = {
    "TITLE": "DineFlow – Notification Service API",
    "DESCRIPTION": """
Notification Service for **DineFlow**.

This service handles:
- Add to Notification
- Remove
- Dish images
- Dish reviews

🔐 Authentication is enforced at the **API Gateway (NGINX)**.
This service trusts headers injected by the gateway.
    """,
    "VERSION": "1.0.0",

    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
            }
        }
    }
}



# -------------------------------------
# Celery Configuration
# -------------------------------------

CELERY_BROKER_URL = "redis://redis:6379/0"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = None
CELERY_IGNORE_RESULT = True

CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = "UTC"

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_WORKER_HIJACK_ROOT_LOGGER = False

CELERY_WORKER_LOG_FORMAT = (
    "[%(asctime)s] [%(levelname)s] [%(processName)s] %(message)s"
)

CELERY_WORKER_TASK_LOG_FORMAT = (
    "[%(asctime)s] [%(levelname)s] [%(task_name)s] %(message)s"
)

CELERY_TASK_DEFAULT_QUEUE = "notification_queue"

# For auto clean up the notification

CELERY_BEAT_SCHEDULE = {
    "delete-readed-notifications-every-morning": {
        "task": "celery_beat.tasks.delete_readed_notifications",
        "schedule": crontab(hour=11, minute=15),
        "options": {"queue": "notification_queue"},
    }
}


import os

# Build the URL dynamically in Python
REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = os.environ.get("REDIS_PORT", "6379")

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL 

# ✅ Update the CHANNEL_LAYERS to use the dynamic variables
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Note the format change: use f-strings or pass a tuple with int port
            "hosts": [(REDIS_HOST, int(REDIS_PORT))], 
        },
    },
}