# Generated by Django 6.0 on 2026-03-31 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(db_index=True, max_length=20)),
                ('dish_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_id', models.CharField(blank=True, max_length=20, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_quick_bites', models.BooleanField(default=False)),
                ('average_rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('prep_time', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('menu_version', models.CharField(db_index=True, default='v1', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant_id', 'dish_id'], name='orders_menu_restaur_87ccb8_idx'), models.Index(fields=['restaurant_id', 'is_available'], name='orders_menu_restaur_984f33_idx'), models.Index(fields=['category_id'], name='orders_menu_categor_e0e2fe_idx'), models.Index(fields=['is_veg'], name='orders_menu_is_veg_eee6c3_idx'), models.Index(fields=['is_popular'], name='orders_menu_is_popu_8408a2_idx'), models.Index(fields=['is_trending'], name='orders_menu_is_tren_86b56a_idx'), models.Index(fields=['total_orders'], name='orders_menu_total_o_64e84a_idx')],
                'unique_together': {('restaurant_id', 'dish_id')},
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('restaurant_id', models.CharField(db_index=True, max_length=20)),
                ('table_public_id', models.CharField(db_index=True, max_length=20)),
                ('table_number', models.CharField(max_length=50)),
                ('zone_public_id', models.CharField(max_length=20)),
                ('zone_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_version', models.CharField(default='v1', max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant_id', 'table_public_id'], name='orders_tabl_restaur_678751_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('restaurant_id', 'table_public_id'), name='unique_active_session_per_table')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('user_id', models.CharField(editable=False, max_length=20)),
                ('restaurant_id', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('special_request', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('table_number', models.CharField(blank=True, null=True)),
                ('table_public_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('zone_name', models.CharField(null=True)),
                ('zone_public_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('waiter_id', models.CharField(blank=True, null=True)),
                ('waiter_name', models.CharField(blank=True, null=True)),
                ('order_by', models.CharField(default='customer')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('order_version', models.CharField(default='v1', max_length=10)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.tablesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(db_index=True, max_length=20)),
                ('restaurant_name', models.CharField(db_index=True, max_length=20)),
                ('table_public_id', models.CharField(db_index=True, max_length=20)),
                ('table_number', models.CharField(max_length=50)),
                ('zone_public_id', models.CharField(max_length=20)),
                ('zone_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_version', models.CharField(default='v1', max_length=10)),
            ],
            options={
                'unique_together': {('restaurant_id', 'table_public_id')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.CharField(db_index=True, max_length=20)),
                ('dish_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item_version', models.CharField(default='v1', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['dish_id'], name='orders_orde_dish_id_9e475c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id', 'created_at'], name='orders_orde_user_id_37fed6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
    ]
