# Generated by Django 6.0 on 2026-03-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(db_index=True, max_length=20)),
                ('dish_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_id', models.CharField(blank=True, max_length=20, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_quick_bites', models.BooleanField(default=False)),
                ('average_rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('prep_time', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('menu_version', models.CharField(db_index=True, default='v1', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant_id', 'dish_id'], name='cart_menuit_restaur_317118_idx'), models.Index(fields=['restaurant_id', 'is_available'], name='cart_menuit_restaur_da5872_idx'), models.Index(fields=['category_id'], name='cart_menuit_categor_027af3_idx'), models.Index(fields=['is_veg'], name='cart_menuit_is_veg_78a9f4_idx'), models.Index(fields=['is_popular'], name='cart_menuit_is_popu_451ca9_idx'), models.Index(fields=['is_trending'], name='cart_menuit_is_tren_a6270a_idx'), models.Index(fields=['total_orders'], name='cart_menuit_total_o_c029c6_idx')],
                'unique_together': {('restaurant_id', 'dish_id')},
            },
        ),
    ]
