# Generated by Django 5.0.3 on 2026-03-31 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('restaurant_id', models.CharField(db_index=True, max_length=20)),
                ('user_public_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=100)),
                ('user_avatar', models.URLField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('show_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_version', models.CharField(db_index=True, default='v1', max_length=20)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dishes.dish')),
            ],
            options={
                'indexes': [models.Index(fields=['dish'], name='idx_review_dish'), models.Index(fields=['user_public_id'], name='idx_review_user'), models.Index(fields=['dish', '-created_at'], name='idx_review_recent')],
            },
        ),
        migrations.AddConstraint(
            model_name='dishreview',
            constraint=models.UniqueConstraint(fields=('dish', 'user_public_id'), name='uniq_review_per_user_per_dish'),
        ),
    ]
