# Generated by Django 5.0.3 on 2026-03-31 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('restaurant_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_version', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='idx_category_active'), models.Index(fields=['name'], name='idx_category_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_category_name'),
        ),
    ]
