"""
Django settings for order_service project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-42=)=f-&yu1u-@_5+^7_b7_-_819h0gm**$__izb5#%emcj+4p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "10.1.0.138:8000",

    # Kubernetes service DNS names
    "auth-service",
    "menu-service",
]

if os.getenv("K8S_ENV") == "true":
    ALLOWED_HOSTS.append("*")

# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "rest_framework",
    'drf_spectacular',
    "orders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.tenant.TenantSchemaMiddleware',
]

ROOT_URLCONF = 'order_service.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]
WSGI_APPLICATION = 'order_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "order_db"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "postgres"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
        "OPTIONS": {
            "options": "-c search_path=public"
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [],
    "UNAUTHENTICATED_USER": None,
}


MENU_SERVICE_URL = os.getenv(
    "MENU_SERVICE_URL",
    "http://menu-service.dineflow-dev.svc.cluster.local:8000"
) 


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', 6379)}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

KAFKA_BROKER = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")




SPECTACULAR_SETTINGS = {
    "TITLE": "DineFlow – Order Service API",
    "DESCRIPTION": """
Order Service for **DineFlow**.

This service handles:
- Add to Order
- Remove
- Dish images
- Dish reviews

🔐 Authentication is enforced at the **API Gateway (NGINX)**.
This service trusts headers injected by the gateway.
    """,
    "VERSION": "1.0.0",

    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
            }
        }
    }
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# -------------------------------------
# Internationalization
# -------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"    
USE_I18N = True
USE_TZ = True


# -------------------------------------
# Celery Configuration
# -------------------------------------

import os

# Fetch the host and port from the environment, falling back to localhost for local development
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")

# Dynamically build the Celery Broker URL
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = None
CELERY_IGNORE_RESULT = True

CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = "UTC"

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_WORKER_HIJACK_ROOT_LOGGER = False

CELERY_WORKER_LOG_FORMAT = (
    "[%(asctime)s] [%(levelname)s] [%(processName)s] %(message)s"
)

CELERY_WORKER_TASK_LOG_FORMAT = (
    "[%(asctime)s] [%(levelname)s] [%(task_name)s] %(message)s"
)

CELERY_TASK_DEFAULT_QUEUE = "order_queue"

# For auto clean up the notification
CELERY_BEAT_SCHEDULE = {
    "close-idle-sessions-every-5-minutes": {
        "task": "orders.tasks.close_idle_sessions",
        "schedule": crontab(minute="*/5"),
        "options": {"queue": "order_queue"},
    },
}

