# Generated by Django 5.0.3 on 2026-03-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('restaurant_id', models.CharField(db_index=True, editable=False, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prep_time', models.PositiveIntegerField(help_text='Estimated time in minutes')),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_quick_bites', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_version', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('image_url', models.URLField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dishes.dish')),
            ],
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['restaurant_id', 'is_available'], name='dishes_dish_restaur_f4554c_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['category', 'is_available'], name='dishes_dish_categor_2a4586_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_veg', 'is_available'], name='dishes_dish_is_veg_c36f33_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_popular'], name='dishes_dish_is_popu_24adea_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_trending'], name='dishes_dish_is_tren_ad914e_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_quick_bites'], name='dishes_dish_is_quic_88f019_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['priority'], name='dishes_dish_priorit_a4e197_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['total_orders'], name='dishes_dish_total_o_7810d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_dish_per_category'),
        ),
        migrations.AddConstraint(
            model_name='dishimage',
            constraint=models.UniqueConstraint(fields=('dish', 'image_url'), name='uniq_dish_image'),
        ),
    ]
