apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-kitchen-consumer
  namespace: dineflow-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-kitchen-consumer
  template:
    metadata:
      labels:
        app: order-kitchen-consumer
    spec:
      containers:
        - name: consumer
          image: dineflow_backend-order_service:latest
          imagePullPolicy: Never
          command:
            - python
            - manage.py
            - consume_kitchen_events
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "host.docker.internal:9092"
            
            - name: REDIS_HOST
              value: "redis"
              
            - name: REDIS_PORT
              value: "6379"

            - name: DB_NAME
              value: "order_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_HOST
              value: "order-db"
            - name: DB_PORT
              value: "5432"