# Generated by Django 6.0.1 on 2026-01-16 16:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('restaurant_id', models.CharField(db_index=True, max_length=20)),
                ('order_id', models.CharField(db_index=True, max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('kitchenTicket_version', models.CharField(default='v1', max_length=10)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status'], name='tickets_kit_status_2643f6_idx'), models.Index(fields=['order_id'], name='tickets_kit_order_i_3a1738_idx')],
            },
        ),
        migrations.CreateModel(
            name='KitchenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(db_index=True, max_length=20)),
                ('dish_id', models.CharField(db_index=True, max_length=20)),
                ('dish_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('prep_time_seconds', models.IntegerField(blank=True, null=True)),
                ('estimated_prep_time_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kitchenItem_version', models.CharField(default='v1', max_length=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.kitchenticket')),
            ],
            options={
                'indexes': [models.Index(fields=['dish_id'], name='tickets_kit_dish_id_fea593_idx'), models.Index(fields=['status'], name='tickets_kit_status_bcb320_idx')],
            },
        ),
    ]
