# Generated by Django 6.0.3 on 2026-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenticket',
            name='table_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
