# Generated by Django 5.0.3 on 2026-03-31 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['role'], name='accounts_cu_role_dceecf_idx'),
        ),
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['restaurant'], name='accounts_cu_restaur_1485aa_idx'),
        ),
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['public_id'], name='accounts_cu_public__237d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['mobile_number', 'restaurant'], name='accounts_cu_mobile__9acd83_idx'),
        ),
        migrations.AddConstraint(
            model_name='customusermodel',
            constraint=models.UniqueConstraint(fields=('restaurant', 'mobile_number'), name='unique_mobile_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='customusermodel',
            constraint=models.UniqueConstraint(condition=models.Q(('restaurant__isnull', True)), fields=('mobile_number',), name='unique_mobile_for_superadmin'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default'], name='accounts_us_user_id_7fa4e4_idx'),
        ),
    ]
