apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-kafka-consumer
  namespace: dineflow-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-kafka-consumer
  template:
    metadata:
      labels:
        app: ai-kafka-consumer
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: consumer
          image: dineflow-ai-service:latest
          imagePullPolicy: IfNotPresent
          command:
            - python
            - -c
            - |
              from app.kafka.menu_consumer import consume_events
              consume_events()
              
            - app.kafka.replay_ai_dlq

          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "host.docker.internal:9092"

            - name: CART_SERVICE_URL
              value: "http://cart-service.dineflow-dev.svc.cluster.local:8000"
              
            - name: ORDERS_SERVICE_URL
              value: "http://order-service.dineflow-dev.svc.cluster.local:8000"

            - name: MENU_SERVICE_URL
              value: "http://menu-service.dineflow-dev.svc.cluster.local:8000"

            - name: POSTGRES_DB
              value: "ai_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST
              value: "ai-db"
            - name: POSTGRES_PORT
              value: "5432"

            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-credentials
                  key: GROQ_API_KEY

          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"