apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-consumer
  namespace: dineflow-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-consumer
  template:
    metadata:
      labels:
        app: notification-consumer
    spec:
      containers:
        - name: consumer
          image: dineflow_backend-notification_service:latest
          imagePullPolicy: Never
          command:
            - python
            - manage.py
            - consume_notifications
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "host.docker.internal:9092"

            - name: DB_NAME
              value: "notification_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_HOST
              value: "notification-db"
            - name: DB_PORT
              value: "5432"

            - name: FIREBASE_CREDENTIALS_PATH
              value: "/secrets/firebase.json"

          volumeMounts:
            - name: firebase-credentials
              mountPath: /secrets
              readOnly: true

      volumes:
        - name: firebase-credentials
          secret:
            secretName: firebase-credentials