apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-celery-beat
  namespace: dineflow-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-celery-beat
  template:
    metadata:
      labels:
        app: notification-celery-beat
    spec:
      containers:
        - name: celery-beat
          image: dineflow_backend-notification_service:latest
          imagePullPolicy: Never  
          command:
            - celery
            - -A
            - notification_service
            - beat
            - -l
            - info
          env:
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/0"
            - name: DJANGO_SETTINGS_MODULE
              value: "notification_service.settings"
            - name: DB_NAME
              value: "notification_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_HOST
              value: "notification-db"
            - name: DB_PORT
              value: "5432"