name: Deploy Notification Service

on:
  push:
    branches: [ main ]
    paths: [ 'notificationService/**', 'k8s/production/notification-service/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/dineflow-notification:latest ./notificationService
          docker push $ECR_REGISTRY/dineflow-notification:latest

      - name: Update KubeConfig
        run: aws eks update-kubeconfig --name dineflow-production-cluster --region ap-south-1

      - name: Deploy to EKS and Restart Pods
        run: |
          kubectl apply -f k8s/production/notification-service/notification-deployment.yaml -n dineflow-production
          
          kubectl rollout restart deployment notification-service -n dineflow-production
          kubectl rollout restart deployment notification-celery-beat -n dineflow-production
          kubectl rollout restart deployment notification-celery-worker -n dineflow-production
          kubectl rollout restart deployment notification-consumer -n dineflow-production
          kubectl rollout restart deployment notification-email-consumer -n dineflow-production
          kubectl rollout restart deployment notification-table-session-consumer -n dineflow-production
          
          # Only checking status on the main API and a worker to save pipeline time
          kubectl rollout status deployment notification-service -n dineflow-production
          kubectl rollout status deployment notification-celery-worker -n dineflow-production