name: Deploy Order Service

on:
  push:
    branches: [ main ]
    paths: [ 'orderService/**', 'k8s/production/order-service/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/dineflow-order:latest ./orderService
          docker push $ECR_REGISTRY/dineflow-order:latest

      - name: Update KubeConfig
        run: aws eks update-kubeconfig --name dineflow-production-cluster --region ap-south-1

      - name: Deploy to EKS and Restart Pods
        run: |
          kubectl apply -f k8s/production/order-service/order-deployment.yaml -n dineflow-production
          
          kubectl rollout restart deployment order-service -n dineflow-production
          kubectl rollout restart deployment order-celery-beat -n dineflow-production
          kubectl rollout restart deployment order-celery-worker -n dineflow-production
          kubectl rollout restart deployment order-kitchen-consumer -n dineflow-production
          kubectl rollout restart deployment order-menu-consumer -n dineflow-production
          kubectl rollout restart deployment order-table-consumer -n dineflow-production
          
          # Only checking status on the main API and a worker to save pipeline time
          kubectl rollout status deployment order-service -n dineflow-production
          kubectl rollout status deployment order-celery-worker -n dineflow-production